# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('department', models.CharField(max_length=55)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.IntegerField()),
                ('name', models.CharField(max_length=55)),
                ('office_number', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
