# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.Professor'),
            preserve_default=False,
        ),
    ]
